urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^paygw/', include('paygw.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #(r'^admin_tools/', include('admin_tools.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^api/', include('api.urls')),
    (r'^assets/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'assets/'}),
    (r'', include('webapp.urls')),
)

webapp/urls.py
from django.conf.urls.defaults import *
from views import TransactionResourceRoot
from views import TransactionResource
import views

urlpatterns = patterns('',
    url(r'^login/?$', 'django.contrib.auth.views.login', {'template_name': 'webapp/login.html'}, name="login"),
    url(r'^logout/?$', 'django.contrib.auth.views.logout_then_login', name="logout"),
    url(r'^update/(?P<tpin>.+)/?$', views.update_transaction, name="update-txn"),
    url(r'^search/?$', views.search_transaction, name="search-txn"),
    url(r'^user/list/?$', views.list_users, name="list-users"),
    url(r'^user/add/?$', views.add_user, name="add-user"),
    url(r'^user/delete/?$', views.delete_user, name="delete-user"),
    url(r'^user/update/(?P<user_id>\d+)/?$', views.update_user, name="update-user"),
    #url(r'^$',                 TransactionResourceRoot.as_view(), name='transaction-resource'),
    url(r'^service/transaction/add/$', TransactionResource.as_view(), name='put-transaction'),
    url(r'^reports/(?P<page>)/?$', views.display_reports, name="display-reports"),
    url(r'^reports/csv/(?P<page>)?$', views.print_to_csv, name="print-to-csv"),
    (r'^$', views.default),
    #url(r'^api/transaction/add', views.put_transaction, name="put-transaction")
)

webapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from audit_log.models.managers import AuditLog
from helpers.fields import UUIDField


""" a tuple of branch code as key and branch name as value """
FINANCIAL_INSTITUTION_BRANCHES = (
    ('BR_CODE1', 'Headquarters, Danmole Street VI'),
    ('BR_CODE2', 'Usman Dan Fodio University Branch'),
)
    
# Create your models here.
class Institution(models.Model):
    """An institution stores details for institutions"""
    name = models.CharField(max_length=100, blank=False)
    code = models.CharField(max_length=32, blank=True, unique=True)
    secret = UUIDField(max_length=32, editable=False)
    
    def __unicode__(self):
        return self.name

class Branch(models.Model):
    """ Branch """
    bid = models.AutoField(primary_key=True)
    institution = models.CharField(max_length=50)
    branchcode = models.CharField(max_length=50)
    name_branch = models.CharField(max_length=50)
    name_branch_short = models.CharField(max_length=50)
    address_1 = models.CharField(max_length=100)
    name_city = models.CharField(max_length=50)
    name_state = models.CharField(max_length=50)
    sector = models.CharField(max_length=50)

    class Meta:
        db_table = u'branch'

    def __unicode__(self):
        return u"%s | %s" % (
            unicode(self.name_branch),
            unicode(self.address_1))

class Transaction(models.Model):
    """Gateway transactions"""
    id = models.AutoField(primary_key=True)
    tpin = UUIDField(max_length=32, blank=True, editable=False,\
        help_text='Transaction Payment Identification Number')
    user_id = models.IntegerField(help_text='The user who made the transaction')
    amount = models.DecimalField(max_digits=14, decimal_places=2, \
        help_text='Transaction amount')
    identifier = models.CharField(max_length=100, blank=True, \
        help_text='A unique identifier provided by the student')
    institution = models.ForeignKey(Institution, related_name='transactions')
    financial_institution = models.ForeignKey('FinancialInstitution', blank=True, null=True, related_name='transactions', help_text='The financial institution this transaction was updated in')
    branch_name = models.ForeignKey(Branch, blank=True, null=True, related_name='transactions', \
        help_text='The bank branch where this transaction is originating from')
    #branch_name_id = models.IntegerField(null=True, blank=True)
    paid = models.BooleanField(default=False)
    teller_no = models.CharField(max_length=20, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    audit_log = AuditLog(exclude=['created', 'updated', ])

    def __unicode__(self):
        return self.tpin

    """def natural_key(self):
        return self.tpin"""

class TransactionTasks(models.Model):
    task_id = models.IntegerField(primary_key=True)
    product_attribute = models.CharField(max_length=30)
    late_registration_date_value = models.IntegerField(null=True, blank=True)
    hostel_reservation_expiry_date_value = models.IntegerField(null=True, blank=True)
    #transaction_tpin_fk = models.CharField(max_length=96) #Should be made a unique field in the db
    transaction_tpin_fk = models.ForeignKey(Transaction, related_name='transactions')
    status = models.CharField(max_length=30)
    task_status = models.CharField(max_length=30)
    class Meta:
        db_table = u'transaction_tasks'
				
class FinancialInstitution(models.Model):
    name = models.CharField(max_length=100)
    #field = 'name_branch'
    #BRANCHES = Branch.objects.values_list('branchcode', field)
    #branch_name = models.CharField(max_length=50,unique=True, choices=BRANCHES)
    #branch_name = models.CharField(max_length=100,unique=True)

    def __unicode__(self):
        return self.name
        """return u"%s | %s" % (
            unicode(self.name),
            unicode(self.branch_name))"""

    @staticmethod
    def get_branches(self, field):
        return Branch.objects.values_list(field, flat=True)


class UserProfile(models.Model):
    """User Profile"""
    user = models.OneToOneField(User)
    supervisor = models.ForeignKey(User, related_name='bank_tellers', null=True, blank=True)
    financial_institution = models.ForeignKey('FinancialInstitution', null=True, blank=True, help_text='The finanacial institution this user belongs to')
    
    def __unicode__(self):
        return self.user.username
        
def user_handler(sender, **kwargs):
    """signal processor for creating a UserProfile for every User"""
    if kwargs['created']:
        profile = UserProfile()
        profile.user = kwargs['instance']
        profile.save()

post_save.connect(user_handler, sender=User)

webapp/views.py
import csv
from django.shortcuts import render_to_response, get_object_or_404
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from django.template import RequestContext as RC
from forms import TransactionUpdateForm, UserCreationForm, UserUpdateForm
#from django.tests.modeltests.reserved_names.models import join
from models import Transaction

import logging

from djangorestframework.resource import Resource
from djangorestframework.response import Response

import django_tables as tables
from helpers.report import TransactionReport
from django.http import HttpResponseNotFound, HttpResponse
from django.template import loader, Context
from django.core import serializers
from django.forms.models import model_to_dict
from django.core.paginator import Paginator, InvalidPage, EmptyPage
import sys

@login_required
def default(request):
    return search_transaction(request)

@login_required
def search_transaction(request):
    context = {'page_title': 'Search Transaction'}
    if request.POST:
        identifier = request.POST.get('identifier', None)
        try:
            qs = Q(financial_institution=None) | Q(financial_institution=request.user.get_profile().financial_institution)
            txn = Transaction.objects.filter(qs).get(identifier=identifier)
            return HttpResponseRedirect(reverse('update-txn', args=[txn.tpin]))
        except Transaction.DoesNotExist:
            request.flash.now['error'] = "Transaction not found"
    return render_to_response("webapp/search_transaction.html", context, context_instance=RC(request))


@login_required
def update_transaction(request, tpin=None):
    qs = Q(financial_institution=None) | Q(financial_institution=request.user.get_profile().financial_institution)
    txn = get_object_or_404(Transaction.objects.filter(qs), tpin=tpin) 
    context = {'page_title': 'Update Transactions'}
    if request.POST:
        update_form = TransactionUpdateForm(request.POST, instance=txn)
        if update_form.is_valid():
            update_form.save()

            # update the financial institution of the transaction to that of the editor
            txn.financial_institution = request.user.get_profile().financial_institution
            txn.save()

            # attached a success message to the flash
            request.flash.now['notice'] = "Transaction updated."
            return HttpResponseRedirect(reverse('search-txn'))
        else:
            # form is invalid
            print update_form.errors
            request.flash.now['error'] = "The update wasn't made due to some errors in the form"
    else:
        update_form = TransactionUpdateForm(instance=txn)
    context['txn'] = txn
    context['form'] = update_form
    return render_to_response("webapp/update_transaction.html", context, context_instance=RC(request))

@permission_required('auth.change_user')
@login_required
def list_users(request):
    user_list = User.objects.filter(userprofile__supervisor=request.user)
    return render_to_response("webapp/list_users.html", {'user_list': user_list }, context_instance=RC(request))

@permission_required('auth.change_user')
@login_required
def add_user(request):
    if request.POST:
        user_form = UserCreationForm(request.POST)
        if user_form.is_valid():
            # create the user and update profile information
            user = User.objects.create_user(user_form.cleaned_data['username'], user_form.cleaned_data['email'], user_form.cleaned_data['password'])
            user.first_name = user_form.cleaned_data['first_name']
            user.last_name = user_form.cleaned_data['last_name']
            user.save()
            profile = user.get_profile()
            profile.supervisor = request.user
            profile.financial_institution = request.user.get_profile().financial_institution
            profile.save()

            request.flash.now['notice'] = "Teller successfully created!"
            user_form = UserCreationForm()
        else:
            errors_list = [user_form.errors[key] for key in user_form.errors.keys()]
            error_messages = ["<br />".join(x) for x in errors_list]
            error_messages = "<br />".join(error_messages)
            request.flash.now['error'] = error_messages
    else:
        user_form = UserCreationForm()

    return render_to_response("webapp/add_user.html", {'form': user_form }, context_instance=RC(request))
            
@permission_required('auth.change_user')
@login_required
def update_user(request, user_id=None):
    user = get_object_or_404(User, userprofile__supervisor=request.user, pk=user_id) 
    if request.POST:
        user_form = UserUpdateForm(request.POST)
        if user_form.is_valid():
            # create the user and update profile information
            user.first_name = user_form.cleaned_data['first_name']
            user.last_name = user_form.cleaned_data['last_name']
            user.email = user_form.cleaned_data['email']
            if user_form.cleaned_data['password']:
                user.set_password(user_form.cleaned_data['password'])
            user.save()

            request.flash.now['notice'] = "Teller successfully updated!"
            user_form = UserUpdateForm()
        else:
            errors_list = [user_form.errors[key] for key in user_form.errors.keys()]
            error_messages = ["<br />".join(x) for x in errors_list]
            error_messages = "<br />".join(error_messages)
            request.flash.now['error'] = error_messages
    else:
        user_form = UserUpdateForm()
    context = {'form': user_form }
    context['user'] = user

    return render_to_response("webapp/update_user.html", context, context_instance=RC(request))

@permission_required('auth.change_user')
@login_required
def delete_user(request):
    if request.POST:
        user_ids = request.POST.getlist('id')
        for user_id in user_ids:
            if user_id.isdigit():
                try:
                    u = User.objects.get(pk=int(user_id),userprofile__supervisor=request.user)
                    u.delete()
                except:
                    pass
    return HttpResponseRedirect(reverse('list-users'))

def put_transaction(request):
    # Get an instance of a logger
    logger = logging.getLogger(__name__)
    logger.info("Called put_transaction")
    #return


class TransactionResourceRoot(Resource):
    allowed_methods = anon_allowed_methods = ('GET')

    def get(self, request, auth):
        return [reverse('put-transaction')]
    
class TransactionResource(Resource):
    """Represents a stored object.
    The object may be any picklable content."""
    allowed_methods = anon_allowed_methods = ('GET', 'PUT', 'POST')

    def get(self, request, content):
        return "GET request"
    
    def post(self, request, auth, content):
        """Handle POST requests"""
        logger = logging.getLogger(__name__)
        logger.info("Called put_transaction")
        return "POST request to StoredObject"

    """
    def get(self, request, auth, key):
        Return a stored object, by unpickling the contents of a locally stored file.
        pathname = os.path.join(OBJECT_STORE_DIR, key)
        if not os.path.exists(pathname):
            return Response(status.HTTP_404_NOT_FOUND)
        return pickle.load(open(pathname, 'rb'))

    def put(self, request, auth, content, key):
        Update/create a stored object, by pickling the request content to a locally stored file.
        pathname = os.path.join(OBJECT_STORE_DIR, key)
        pickle.dump(content, open(pathname, 'wb'))
        return content

        """

@login_required
def display_reports(request, **kwargs):
    #data = Transaction.objects.all()
    logger = logging.getLogger(__name__)
    try:
        dataqs = Transaction.objects.filter(paid="TRUE")
    except Transaction.DoesNotExist:
        dataqs = None
    #req = request.GET.get('sort', 'created')
    #transactions = TransactionReport(dataqs, order_by=request.GET.get('sort', 'created'))
    #tx = TransactionReport().get_reports_paid(dataqs, req)
    SHOW_CONTENT_LIMIT = 2
    paginate_list = Paginator(dataqs, SHOW_CONTENT_LIMIT)
    start_req_page = request.GET.get(u'page', 1).__str__() #converts start_req_page to string
    if start_req_page.isdigit():
        page_no = int(request.GET.get(u'page', 1))
    else:
        print u'The variable String contains no digit'
    try:
        contents = paginate_list.page(page_no)
    except (EmptyPage, InvalidPage):
        contents = paginate_list.page(paginate_list.num_pages)
    total_pages_list = range(1,  paginate_list.num_pages + 1)# a list of arithmetic progressions e.g 1,2...
    #print dir(contents) #dir is similar to print_r
    #print dir(contents.object_list)
    #print dir(contents.object_list.model)

    x = {contents.number:contents.object_list}

    request.session['contents'] = x

    #page_session_data = request.session['contents']
    #print request.session['contents']
    
    #return render_to_response('webapp/reports.html', {'table': transactions})
    return render_to_response('webapp/reports.html', {'table': dataqs, 'contents':contents,'total_pages_list':total_pages_list}, context_instance=RC(request))

    #return HttpResponse(tx)



# call report_to_csv. url = report/csv
def print_to_csv(request, **kwargs):
    response = HttpResponse(mimetype='text/csv')
    response['Content-Disposition'] = 'attachment; filename=report_csv.csv'

    #response = HttpResponse(pickle.dumps(entry_list),mimetype='application/x-pickle.python')
    

webapp/templates/webapp/add_user.html
{% extends "layout_user.html" %}
{% load humanize %}
{% block content %}
<div class="block">
	{% if flash %}
	<div class="flash">
		{% for type, message in flash.items %}
			<div class="message {{ type }}">
				<p>{{ message|safe }}</p>
			</div>
		{% endfor %}
	</div>
	{% endif %}
	<div class="secondary-navigation">
		<ul class="wat-cf">
			<li class="first"><a href="{% url list-users %}">Bank Tellers</a></li>
			<li class="active"><a href="{% url add-user %}">Create Teller</a></li>
		</ul>
	</div>
	<div class="content">
		<h2 class="title">Create Teller</h2>
		<div class="inner">
			<form action="{% url add-user %}" method="post" class="form">
				<div class="group">
					<label for="{{ form.username.name }}" class="label">{{ form.username.label }}</label>
					{{ form.username }}
					{{ form.username.help_text }}
				</div>
				<div class="group">
					<label for="{{ form.password.name }}" class="label">{{ form.password.label }}</label>
					{{ form.password }}
					{{ form.password.help_text }}
				</div>
				<div class="group">
					<label for="{{ form.password_verify.name }}" class="label">{{ form.password_verify.label }}</label>
					{{ form.password_verify }}
					{{ form.password_verify.help_text }}
				</div>
				<div class="group">
					<label for="{{ form.first_name.name }}" class="label">{{ form.first_name.label }}</label>
					{{ form.first_name }}
				</div>
				<div class="group">
					<label for="{{ form.last_name.name }}" class="label">{{ form.last_name.label }}</label>
					{{ form.last_name }}
				</div>
				<div class="group">
					<label for="{{ form.email.name }}" class="label">{{ form.email.label }}</label>
					{{ form.email }}
				</div>
				<div class="group navform wat-cf">
					<button class="button" type="submit">
						<img src="/assets/images/icons/plus.png" alt="Create"> Create
					</button>
					<a href="{% url list-users %}" class="button"><img src="/assets/images/icons/cross.png" alt="Cancel"> Cancel</a>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

webapp/templates/webapp/list_users.html
{% extends "layout_user.html" %}
{% load humanize %}
{% block javascripts %}
   <script src="/assets/js/jquery-1.4.4.min.js" type="text/javascript" charset="utf-8"></script>
	 <script type="text/javascript" charset="utf-8">
		$(document).ready(function () {
			$('.table :checkbox.toggle').each(function(i, toggle) {
        $(toggle).change(function(e) {
          $(toggle).parents('table:first').find(':checkbox:not(.toggle)').each(function(j, checkbox) {
            checkbox.checked = !checkbox.checked;
          })
        });
      });

			$('#form').submit(function () {
				return confirm('Are you sure you want to delete these tellers?');
			});
		});
	 </script>
{% endblock %}
{% block content %}
<div class="block">
	{% if flash %}
	<div class="flash">
		{% for type, message in flash.items %}
			<div class="message {{ type }}">
				<p>{{ message|safe }}</p>
			</div>
		{% endfor %}
	</div>
	{% endif %}
	<div class="secondary-navigation">
		<ul class="wat-cf">
			<li class="first active"><a href="{% url list-users %}">Bank Tellers</a></li>
			<li><a href="{% url add-user %}">Create Teller</a></li>
		</ul>
	</div>
	<div class="content">
		<h2 class="title">Bank Tellers</h2>
		<div class="inner">
			<form action="{% url delete-user %}" method="post" class="form" id="form">
				<table class="table">
					<tbody>
						<tr>
							<th class="first"><input type="checkbox" class="checkbox toggle"></th>
							<th>Username</th>
							<th>First Name</th>
							<th>Last Name</th>
							<th>Email</th>
							<th class="last">&nbsp;</th>
						</tr>
						{% for user in user_list %}
						<tr class="{% cycle 'odd' 'even' %}">
							<td><input type="checkbox" name="id" value="{{ user.pk }}" class="checkbox" /></td>
							<td>{{ user.username }}</td>
							<td>{{ user.first_name|default:'&nbsp;' }}</td>
							<td>{{ user.last_name|default:'&nbsp;' }}</td>
							<td>{{ user.email|default:'&nbsp;' }}</td>
							<td class="last"><a href='{% url update-user user.pk %}'>edit</a></td>
						</tr>
						{% empty %}
						<tr class="odd">
							<td colspan="6" style='text-align:center'>No bank tellers. <a href="{% url add-user %}">Click here</a> to create one.</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
				<div class="actions-bar wat-cf">
					<div class="actions">
						<button class="button" type="submit">
							<img src="/assets/images/icons/minus-circle.png" alt="Save"> Delete
						</button>
						<a href="{% url search-txn %}" class="button"><img src="/assets/images/icons/cross.png" alt="Cancel"> Cancel</a>
					</div>
					<div class="pagination">
						<span class="disabled prev_page">« Previous</span><span class="current">1</span><a rel="next" href="#">2</a><a href="#">3</a><a href="#">4</a><a href="#">5</a><a href="#">6</a><a href="#">7</a><a href="#">8</a><a href="#">9</a><a href="#">10</a><a href="#">11</a><a rel="next" class="next_page" href="#">Next »</a>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

webapp/templates/webapp/login.html
{% extends "layout.html" %}
{% load settings %}
{% block content %}
<h1>{% setting APP_NAME %}</h1>
<div class="block" id="block-login">
  <h2>Sign In</h2>        
  <div class="content login">
		{% if form.errors %}
    <div class="flash">
      <div class="message error">
        <p>Your username and password didn't match.<br />Please try again.</p>
      </div>
    </div>
		{% endif %}
		<form action="{% url django.contrib.auth.views.login %}" method="post" accept-charset="utf-8">
			{% csrf_token %}
      <div class="group wat-cf">
        <div class="left">
          <label class="label right">{{ form.username.label }}</label>
        </div>
        <div class="right">
					<input type="text" name="{{ form.username.name }}" value="{{ form.initial.username }}">
        </div>              
      </div>
      <div class="group wat-cf">
        <div class="left">
          <label class="label right">{{ form.password.label }}</label>
        </div>
        <div class="right">
					<input type="password" name="{{ form.password.name }}" value="{{ form.initial.password }}">
        </div>              
      </div>
      <div class="group navform wat-cf">
        <div class="right">
          <input type="submit" class="button" value="Sign In &rarr;" />
        </div>
      </div>            
		</form>
  </div>
</div>
{% endblock %}

webapp/templates/webapp/reports.html
{% extends "layout_user.html" %}
{% load humanize %}

{% block content %}
<div class="block">
	{% if flash %}
	<div class="flash">
		{% for type, message in flash.items %}
			<div class="message {{ type }}">
				<p>{{ message|safe }}</p>
			</div>
		{% endfor %}
	</div>
	{% endif %}
    <div class="secondary-navigation">
		<ul class="wat-cf">
			<li class="first"><a href="{% url list-users %}">Bank Tellers</a></li>
			<li><a href="{% url add-user %}">Create Teller</a></li>
			<li class="active"><a href="{% url display-reports page %}">View Reports</a></li>
		</ul>
	</div>
	<div class="content">
		<h2 class="title">View Reports</h2>
		<div class="inner">
                    <table class="table">
                        <tbody>
                            <tr>
                                    <th class="first">S/N</th>
                                    <th>Amount</th>
                                    <th>Teller No.</th>
                                    <th>Paid</th>
                                    <th>University</th>
                                    <th>Bank</th>
                                    <th>Bank branch</th>
                                    <th>Paid date</th>
                                    <th class="last">Updated</th>
                            </tr>
                            {% for obj in contents.object_list %}
                                <tr class="{% cycle 'odd' 'even' %}">
                                    <td>{{ obj.id }}</td>
                                    <td>{{ obj.amount }}</td>
                                    <td>{{ obj.teller_no }}</td>
                                    <td>{{ obj.paid }}</td>
                                    <td>{{ obj.institution_id }}</td>
                                    <td>{{ obj.financial_institution_id }}</td>
                                    <td>{{ obj.branch_name_id }}</td>
                                    <td>{{ obj.created }}</td>
                                    <td>{{ obj.updated }}</td>
                                </tr>
                            {% endfor %}
                        <tbody>
                    </table>
                    <table class="table">
                        <tbody>
                        <tr>
                            {% for column in table.columns %}
                            <th {% if forloop.first %} class="first" {% endif %} {% if forloop.last %} class="last" {% endif %} class="table-header">
                                {% if column.sortable %}
                                  <a href="?sort={{ column.name_toggled }}">
                                    {{ column }}  
                                  </a>
                                {% endif %}
                            </th>
                            {% endfor %}
                        </tr>
                        {% for row in table.rows %}
                          <tr class="{% cycle 'odd' 'even' %}">
                          {% for value in row %}
                            <td class="table-data">{{ value }}<td>
                          {% endfor %}
                          </tr>
                        {% endfor %}
                        </tbody>
                    </table>{{contents.number}}{{contents.object_list}}
                    <div class="actions-bar wat-cf">
                        <div class="actions">
                                <button class="button" type="submit">
                                        <img src="/assets/images/icons/minus-circle.png" alt="Save"> Delete
                                </button>
                                <a target="_blank" href="{% url print-to-csv %}?page={{contents.number}}" class="button"><img src="/assets/images/icons/cross.png" alt="Cancel"> Print to CSV</a>
                        </div>
                        <div class="pagination">
                            <span class="disabled prev_page">
                            {% if contents.has_previous %}
                             <a href = "?page = {{contents.previous_page_number}}"> Previous </a>
                             {% endif %}
                             <span class="current">
                             {% for page_number in total_pages_list %}
                                   {% ifequal page_number contents.number %}
                                   <a href="?page={{page_number}}" class="clsActive" title="Current Page">{{contents.number}}</a>
                                   {% else %}
                                   <a id = "currentpage" class = "currentpage" href="?page={{page_number}}">{{page_number}}</a>
                                   {% endifequal %}
                             {% endfor %}
                             </span>

                             {% if contents.has_next %}
                              <a rel="next" class="next_page" href="?page={{contents.next_page_number}}"> Next </a>
                             {% endif %}
                            </span>
                         </div
                    </div>
                </div>
        </div>
</div>
{% endblock %}

webapp/templates/webapp/test.html
error

webapp/templates/webapp/update_transaction.html
{% extends "layout_transactions.html" %}
{% load humanize %}
{% block content %}
<div class="block">
	{% if flash %}
	<div class="flash">
		{% for type, message in flash.items %}
			<div class="message {{ type }}">
				<p>{{ message|safe }}</p>
			</div>
		{% endfor %}
	</div>
	{% endif %}
	<div class="secondary-navigation">
		<ul class="wat-cf">
			<li class="first"><a href="{% url search-txn %}">Search Transaction</a></li>
			<li class="active"><a href="javascript:;">Update Transaction</a></li>
		</ul>
	</div>
	<div class="content">
		<h2 class="title">Update Transaction</h2>
		<div class="inner">
			<form action="{% url update-txn txn.tpin %}" method="post" class="form">
				<div class="group">
					<label class="label">Transaction Reference</label>
					<input class="text_field" type="text" disabled="disabled" value="{{ txn.tpin }}" />
				</div>
				<div class="group">
					<label class="label">Identifier</label>
					<input class="text_field" type="text" disabled="disabled" value="{{ txn.identifier }}" />
				</div>
				<div class="group">
					<label class="label">Institution</label>
					<input class="text_field" type="text" disabled="disabled" value="{{ txn.institution }}" />
				</div>
                                <div class="group">
					<!--<label class="label">Branch name</label>
					<input class="text_field" type="text" disabled="disabled" value="" />-->
                                        <label class="label" for="id_branch_name">Branch name: </label>
                                        {{form.branch_name}}
                                        <!--<select name="branch_name" class="form-select " id="id_branch_name" >
                                            <option value="0">Incomplete grade</option>
                                        </select>-->
				</div>
				<div class="group">
					<label class="label">Amount</label>
					<input class="text_field" type="text" disabled="disabled" value="&#x20a6 {{ txn.amount|intcomma }}" />
				</div>
				<div class="group">
					<label class="label">Teller No.</label>
					<input class="text_field" type="text" name="{{ form.teller_no.name }}" value="{{ form.initial.teller_no }}" />
					<span class="description">The teller number on the payment slip</span>
				</div>
				<div class="group">
					<label class="label">Paid</label>
					<input class="text_field" style="display:block" type="checkbox" name="{{ form.paid.name }}" value="True"{% if form.initial.paid %} checked="checked"{% endif %} />
					<span class="description">Tick this box to mark this transaction as paid for</span>
				</div>
				<div class="group navform wat-cf">
					<button class="button" type="submit">
						<img src="/assets/images/icons/tick.png" alt="Save"> Save
					</button>
					<a href="{% url search-txn %}" class="button"><img src="/assets/images/icons/cross.png" alt="Cancel"> Cancel</a>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}